In [6]:
import sqlite3
from src.utils import sql_to_df, selecc_features,train_test_split_selector,model_baseline_train,model_baseline_evaluate,calcular_ndcg_por_usuario,calcular_feature_importance,entrenamiento_modelo_final,prediccion_usuarios_final,preparacion_envio

In [2]:
exp_test ="exp_test"
seed = 42
df = sql_to_df()
features_drop = []
feat_selecc = selecc_features(features_drop)
df_train , df_test = train_test_split_selector(df,seed)
model = model_baseline_train(df_train ,feat_selecc , seed )
metrics = model_baseline_evaluate(df_test ,feat_selecc ,model,exp_test )
ndcg_medio_5 = calcular_ndcg_por_usuario(df_test,exp_test)
ndcg_medio_20 = calcular_ndcg_por_usuario(df_test,exp_test,20)
df_importances = calcular_feature_importance(model,exp_test)

************************************ Comienzo creacion dataframe ************************************
df shape: (461074, 22)
************************************ Comienzo seleccion features ************************************
Features Seleccionadas : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'rating_promedio_usuario_te', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
************************************ Comenzando split train test ************************************
df_train shape : (368859, 22)
df_test shape : (92215, 22)
************************************ Comienzo entrenamiendo modelo base ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'rating_promedio_usuario_te', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004144 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7883
[LightGBM] [Info] Number of data points in the train set: 368859, number of used features: 14
[LightGBM] [Info] Start training from score 7.265725
************************************ Comienzo evaluaciones del experimento exp_test ************************************

=== Resultados del Baseline ===
RMSE:  1.5527
MAE:   1.1735
R2:    0.2785
************************************ Comienzo calculo NDCG del experimento exp_test ************************************
Usuarios evaluados con >= 5 libros: 3685
NDGC MEDIO = 0.958744171867714
************************************ Comienzo calculo NDCG del experimento exp_test ************************************
Usuarios evaluados con >= 20 libros: 1285
NDGC MEDIO = 0.9571892031766012
************************************ Calculando Feature Importances ************************************

In [6]:
df_importances

                            Feature  Split          Gain  Gain_Porcentaje
0        rating_promedio_usuario_te    185  1.133922e+06        53.678668
1                             autor   1660  6.804634e+05        32.212427
2                         editorial    310  6.962249e+04         3.295856
3                   volumen_lectura     67  5.763234e+04         2.728255
4        desviacion_estandar_rating    289  5.697682e+04         2.697223
5                           vive_en    267  3.857254e+04         1.825984
6                      genero_libro     73  3.431802e+04         1.624579
7                       cant_nuevos     34  2.642633e+04         1.250995
8           genero_favorito_usuario     35  4.151476e+03         0.196527
9                      anio_edicion     41  4.009556e+03         0.189808
10                           genero     15  3.955198e+03         0.187235
11  ratio_libros_antiguos_vs_nuevos     12  1.289336e+03         0.061036
12                    cant_antiguos      5  7.181906e+02         0.033998
13                       nacimiento      7  3.677471e+02         0.017409

In [3]:
modelo_lgbm ,feat_imp_final=entrenamiento_modelo_final(df,feat_selecc,42,exp_test)

************************************ Comienzo entrenamiendo modelo base final :exp_test ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'rating_promedio_usuario_te', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005525 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7911
[LightGBM] [Info] Number of data points in the train set: 461074, number of used features: 14
[LightGBM] [Info] Start training from score 7.263422
Modelo guardado exitosamente en: outputs/scripts/modelos_finales/modelo_final_exp_test.pkl
************************************ Calculando Feature Importances ************************************
feat importances guardado en : outputs/scripts/modelos_finales/feat_imp_exp_test_final.csv

In [4]:
resultados_dict=prediccion_usuarios_final(df,feat_selecc,modelo_lgbm,exp_test)

************************************ Comienzo prediccion final ************************************
el id:102893014085601872783 entra a ids_no_inter_si_lectores
¡Proceso para el id 102893014085601872783 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:103084137542939876557 entra a ids_no_inter_si_lectores
¡Proceso para el id 103084137542939876557 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:104186425412399255991 entra a ids_no_inter_si_lectores
¡Proceso para el id 104186425412399255991 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:114281238546612894708 entra a ids_no_inter_si_lectores
¡Proceso para el id 114281238546612894708 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:115834876939320404006 entra a ids_no_inter_si_lectores
¡Proceso para el id 115834876939320404006 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:115884316008551273059 entra a ids_no_inter_si_lectores
¡Proceso para el id 115884316008551273059 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:116044910452339432768 entra a ids_no_inter_si_lectores
¡Proceso para el id 116044910452339432768 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 14-de-abril terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 1570763926343197 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 1871059736242584 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 1948jaas terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 2095121037214269 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 3r terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 3ug3nio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id 690663634460200 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id a-rigald terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id aaron terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id abaquo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id abernalz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id abrasianes terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id abredu terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:acastrop entra a ids_no_inter_si_lectores
¡Proceso para el id acastrop terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id acatasus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id admillencolin terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id adri-triana terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id adrianqll terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id afb14 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id afraile terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id agentependelgast terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id agus1789 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ainhoa terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id al1980 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alaincharnier terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id albasit terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alber84 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alberto22 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id albertogonzalez terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id albertovep terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id albertu terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alcasa terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alcosecha terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alejandra123 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alejandroparadissandstromatgmailcom terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alevelguz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alex-1983 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alex-asensi terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alex-lopeznavas terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alexim00 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alfes terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alfonsoac terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id allddo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id almudena terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id almudena-alaminos terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:alpasil entra a ids_si_inter_no_lectores
¡Proceso para el id alpasil terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alvaro1121 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alvarocf terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alvata terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id alvgar terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id amorales78 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id amosis terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id amparix terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id amurillo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ana-g-aranda terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ana-lopi-lopezuela terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ana797 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anabel-li terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anabel_rguez92 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anadandrea terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anajordiana terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id analeo11 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anard terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id andriussupp terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id andrixo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id angel8 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id angela_majaron terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id angelus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id angiir terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id anpiba terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id antmarmol terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id antonio-gutierrezespinosa-14 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id antonio-martinmorales-98 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id antoniocanogomez terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id antonioe terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id apm_93 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id aqualung terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id aracelism terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id arbonaida terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id armandilio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id armonia7 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id arnau12345 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ars terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id arti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id asito29 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id astronauta-sideral terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id asuncion74 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id avalencia terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id avilechuti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id awaintal terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id az-123 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id azrael terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id balbo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bartolotta1996 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bathorybora terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id batidor terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id beapgz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id beer terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bellacolance terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id benelux terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id berenga45 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bicho terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bitoledo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bitw1010 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id blanca-toral-r terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id blancarmo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id blaugir terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bolanodiccion terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bonifacio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id borjakhet terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bosquet terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id boticarrera terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bravogon terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id breogan1945 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bugatti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id buho terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id bulsara26 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id burek terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cagupe terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id campa112 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carislm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carlanga terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carlexo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carlosc terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
el id:carlosecheve entra a ids_no_inter_si_lectores
¡Proceso para el id carlosecheve terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carlosgreif terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carlosjesus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carmen2013 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carmenguerrero terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id caroline-moran terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id carrodug terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id castilla terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cati-roig terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id ccasconm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cchema terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cesarportillo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chattanooga terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chelow terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chemab terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chero terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chicaraspa terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chinchanpen terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chriistina-21 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id chui terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cintiagarcia75 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id claramp terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id claudia-caballero terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cmarcelo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id condor terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id conxirj terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id copi13 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id coprolito76 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cosmos terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cota49 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id cramald terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json
¡Proceso para el id crismarel terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test.json

In [5]:
resultados_finales = preparacion_envio(exp_test)

CSV final generado en: outputs/scripts/modelos_finales/results_finales_exp_test.csv

In [2]:
exp_test ="exp_test_2"
seed = 42
df = sql_to_df()
features_drop = ['rating_promedio_usuario_te']
feat_selecc = selecc_features(features_drop)
df_train , df_test = train_test_split_selector(df,seed)
model = model_baseline_train(df_train ,feat_selecc , seed )
metrics = model_baseline_evaluate(df_test ,feat_selecc ,model,exp_test )
ndcg_medio_5 = calcular_ndcg_por_usuario(df_test,exp_test)
ndcg_medio_20 = calcular_ndcg_por_usuario(df_test,exp_test,20)
df_importances = calcular_feature_importance(model,exp_test)

************************************ Comienzo creacion dataframe ************************************
df shape: (461074, 22)
************************************ Comienzo seleccion features ************************************
Features Seleccionadas : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
************************************ Comenzando split train test ************************************
df_train shape : (368859, 22)
df_test shape : (92215, 22)
************************************ Comienzo entrenamiendo modelo base ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7628
[LightGBM] [Info] Number of data points in the train set: 368859, number of used features: 13
[LightGBM] [Info] Start training from score 7.265725
************************************ Comienzo evaluaciones del experimento exp_test_2 ************************************

=== Resultados del Baseline ===
RMSE:  1.6309
MAE:   1.2497
R2:    0.2040
************************************ Comienzo calculo NDCG del experimento exp_test_2 ************************************
Usuarios evaluados con >= 5 libros: 3685
NDGC MEDIO = 0.9586911352771914
************************************ Comienzo calculo NDCG del experimento exp_test_2 ************************************
Usuarios evaluados con >= 20 libros: 1285
NDGC MEDIO = 0.9569561039881482
************************************ Calculando Feature Importances ************************************

In [3]:
df_importances

                            Feature  Split           Gain  Gain_Porcentaje
0                             autor   1539  817226.616581        48.318239
1                           vive_en    522  324858.635521        19.207154
2        desviacion_estandar_rating    203  187494.782784        11.085564
3                         editorial    294  101888.720963         6.024135
4                       cant_nuevos     35   91836.305393         5.429790
5                      genero_libro     61   66470.467297         3.930043
6                   volumen_lectura     81   34373.437969         2.032318
7           genero_favorito_usuario     66   25990.442989         1.536676
8                     cant_antiguos     52   13829.152912         0.817644
9   ratio_libros_antiguos_vs_nuevos     35   10458.923553         0.618380
10                       nacimiento     43    6912.345211         0.408690
11                     anio_edicion     43    5944.319365         0.351456
12                           genero     26    4057.744335         0.239913

In [4]:
modelo_lgbm ,feat_imp_final=entrenamiento_modelo_final(df,feat_selecc,42,exp_test)

************************************ Comienzo entrenamiendo modelo base final :exp_test_2 ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003341 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7656
[LightGBM] [Info] Number of data points in the train set: 461074, number of used features: 13
[LightGBM] [Info] Start training from score 7.263422
Modelo guardado exitosamente en: outputs/scripts/modelos_finales/modelo_final_exp_test_2.pkl
************************************ Calculando Feature Importances ************************************
feat importances guardado en : outputs/scripts/modelos_finales/feat_imp_exp_test_2_final.csv

In [5]:
resultados_dict=prediccion_usuarios_final(df,feat_selecc,modelo_lgbm,exp_test)

************************************ Comienzo prediccion final ************************************
Ya esta completado el json de los resultados : outputs/scripts/modelos_finales/checkpoint_exp_test_2.json !! Pasar a la preparacion del envio

In [11]:
resultados_finales = preparacion_envio(exp_test)

CSV final generado en: outputs/scripts/modelos_finales/results_finales_exp_test_2.csv

In [7]:
exp_test ="exp_test_3"
seed = 42
df = sql_to_df()
features_drop = ['rating_promedio_usuario_te']
feat_selecc = selecc_features(features_drop)
df_train , df_test = train_test_split_selector(df,seed)
model = model_baseline_train(df_train ,feat_selecc , seed )
metrics = model_baseline_evaluate(df_test ,feat_selecc ,model,exp_test )
ndcg_medio_5 = calcular_ndcg_por_usuario(df_test,exp_test)
ndcg_medio_20 = calcular_ndcg_por_usuario(df_test,exp_test,20)
df_importances = calcular_feature_importance(model,exp_test)

************************************ Comienzo creacion dataframe ************************************
df shape: (461074, 22)
************************************ Comienzo seleccion features ************************************
Features Seleccionadas : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
************************************ Comenzando split train test ************************************
df_train shape : (368859, 22)
df_test shape : (92215, 22)
************************************ Comienzo entrenamiendo modelo base ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010209 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7628
[LightGBM] [Info] Number of data points in the train set: 368859, number of used features: 13
[LightGBM] [Info] Start training from score 7.265725
************************************ Comienzo evaluaciones del experimento exp_test_3 ************************************

=== Resultados del Baseline ===
RMSE:  1.6309
MAE:   1.2497
R2:    0.2040
************************************ Comienzo calculo NDCG del experimento exp_test_3 ************************************
Usuarios evaluados con >= 5 libros: 3685
NDGC MEDIO = 0.9586911352771914
************************************ Comienzo calculo NDCG del experimento exp_test_3 ************************************
Usuarios evaluados con >= 20 libros: 1285
NDGC MEDIO = 0.9569561039881482
************************************ Calculando Feature Importances ************************************

In [8]:
df_importances

                            Feature  Split           Gain  Gain_Porcentaje
0                             autor   1539  817226.616581        48.318239
1                           vive_en    522  324858.635521        19.207154
2        desviacion_estandar_rating    203  187494.782784        11.085564
3                         editorial    294  101888.720963         6.024135
4                       cant_nuevos     35   91836.305393         5.429790
5                      genero_libro     61   66470.467297         3.930043
6                   volumen_lectura     81   34373.437969         2.032318
7           genero_favorito_usuario     66   25990.442989         1.536676
8                     cant_antiguos     52   13829.152912         0.817644
9   ratio_libros_antiguos_vs_nuevos     35   10458.923553         0.618380
10                       nacimiento     43    6912.345211         0.408690
11                     anio_edicion     43    5944.319365         0.351456
12                           genero     26    4057.744335         0.239913

In [9]:
modelo_lgbm ,feat_imp_final=entrenamiento_modelo_final(df,feat_selecc,42,exp_test)

************************************ Comienzo entrenamiendo modelo base final :exp_test_3 ************************************
Features seleccionadas para el entrenamiento : ['genero', 'vive_en', 'nacimiento', 'autor', 'genero_libro', 'editorial', 'anio_edicion', 'volumen_lectura', 'desviacion_estandar_rating', 'genero_favorito_usuario', 'cant_antiguos', 'cant_nuevos', 'ratio_libros_antiguos_vs_nuevos']
Target : rating
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003339 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 7656
[LightGBM] [Info] Number of data points in the train set: 461074, number of used features: 13
[LightGBM] [Info] Start training from score 7.263422
Modelo guardado exitosamente en: outputs/scripts/modelos_finales/modelo_final_exp_test_3.pkl
************************************ Calculando Feature Importances ************************************
feat importances guardado en : outputs/scripts/modelos_finales/feat_imp_exp_test_3_final.csv

In [10]:
resultados_dict=prediccion_usuarios_final(df,feat_selecc,modelo_lgbm,exp_test)

************************************ Comienzo prediccion final ************************************
Aun no se comenzo con los resultados finales del exp : exp_test_3
¡Proceso para el id 05-03-1970 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 05131344k terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10155384625823370 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10155485526803149 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10155504435866506 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10155829844135513 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10156836858139172 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10211963785346339 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10212952931491505 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10213841146374182 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10214004947708283 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10215155402982506 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 10215796177443356 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:102893014085601872783 entra a ids_no_inter_si_lectores
¡Proceso para el id 102893014085601872783 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:103084137542939876557 entra a ids_no_inter_si_lectores
¡Proceso para el id 103084137542939876557 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:104186425412399255991 entra a ids_no_inter_si_lectores
¡Proceso para el id 104186425412399255991 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:114281238546612894708 entra a ids_no_inter_si_lectores
¡Proceso para el id 114281238546612894708 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:115834876939320404006 entra a ids_no_inter_si_lectores
¡Proceso para el id 115834876939320404006 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:115884316008551273059 entra a ids_no_inter_si_lectores
¡Proceso para el id 115884316008551273059 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:116044910452339432768 entra a ids_no_inter_si_lectores
¡Proceso para el id 116044910452339432768 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 14-de-abril terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 1570763926343197 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 1871059736242584 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 1948jaas terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 2095121037214269 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 3r terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 3ug3nio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id 690663634460200 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id a-rigald terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id aaron terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id abaquo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id abernalz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id abrasianes terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id abredu terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:acastrop entra a ids_no_inter_si_lectores
¡Proceso para el id acastrop terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id acatasus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id admillencolin terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id adri-triana terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id adrianqll terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id afb14 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id afraile terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id agentependelgast terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id agus1789 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ainhoa terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id al1980 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alaincharnier terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id albasit terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alber84 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alberto22 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id albertogonzalez terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id albertovep terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id albertu terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alcasa terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alcosecha terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alejandra123 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alejandroparadissandstromatgmailcom terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alevelguz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alex-1983 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alex-asensi terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alex-lopeznavas terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alexim00 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alfes terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alfonsoac terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id allddo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id almudena terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id almudena-alaminos terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:alpasil entra a ids_si_inter_no_lectores
¡Proceso para el id alpasil terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alvaro1121 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alvarocf terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alvata terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id alvgar terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id amorales78 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id amosis terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id amparix terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id amurillo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ana-g-aranda terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ana-lopi-lopezuela terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ana797 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anabel-li terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anabel_rguez92 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anadandrea terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anajordiana terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id analeo11 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anard terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id andriussupp terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id andrixo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id angel8 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id angela_majaron terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id angelus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id angiir terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id anpiba terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id antmarmol terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id antonio-gutierrezespinosa-14 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id antonio-martinmorales-98 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id antoniocanogomez terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id antonioe terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id apm_93 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id aqualung terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id aracelism terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id arbonaida terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id armandilio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id armonia7 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id arnau12345 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ars terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id arti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id asito29 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id astronauta-sideral terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id asuncion74 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id avalencia terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id avilechuti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id awaintal terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id az-123 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id azrael terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id balbo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bartolotta1996 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bathorybora terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id batidor terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id beapgz terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id beer terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bellacolance terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id benelux terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id berenga45 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bicho terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bitoledo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bitw1010 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id blanca-toral-r terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id blancarmo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id blaugir terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bolanodiccion terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bonifacio terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id borjakhet terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bosquet terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id boticarrera terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bravogon terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id breogan1945 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bugatti terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id buho terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id bulsara26 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id burek terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id cagupe terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id campa112 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carislm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carlanga terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carlexo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carlosc terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
el id:carlosecheve entra a ids_no_inter_si_lectores
¡Proceso para el id carlosecheve terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carlosgreif terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carlosjesus terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carmen2013 terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carmenguerrero terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id caroline-moran terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id carrodug terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id castilla terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id cati-roig terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id ccasconm terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id cchema terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id cesarportillo terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id chattanooga terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id chelow terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json
¡Proceso para el id chemab terminado. Respaldo JSON en: outputs/scripts/modelos_finales/checkpoint_exp_test_3.json

In [11]:
resultados_finales, resultados_con_scores =preparacion_envio(exp_test)

CSV para Kaggle generado en: outputs/scripts/modelos_finales/results_finales_exp_test_3.csv
CSV de análisis con scores generado en: outputs/scripts/modelos_finales/results_finales_exp_test_3_con_scores.csv